apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-po-es7.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: conductor-elasticsearch
  name: conductor-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: conductor-elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-po-es7.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/internal: "true"
        io.kompose.service: conductor-elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx1024m
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
          livenessProbe:
            exec:
              command:
                - curl http://localhost:9200/_cluster/health -o /dev/null
            failureThreshold: 12
            periodSeconds: 5
            timeoutSeconds: 5
          name: conductor-elasticsearch
          ports:
            - containerPort: 9200
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: esdata-conductor
      restartPolicy: Always
      volumes:
        - name: esdata-conductor
          persistentVolumeClaim:
            claimName: esdata-conductor
status: {}
