apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-po-es7.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: conductor-server
  name: conductor-server
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: conductor-server
status:
  loadBalancer: {}
