apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-po-es7.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: conductor-server
  name: conductor-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: conductor-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-po-es7.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/internal: "true"
        io.kompose.service: conductor-server
    spec:
      containers:
        - env:
            - name: CONFIG_PROP
              value: config-postgres-es7.properties
          image: conductor:server
          livenessProbe:
            exec:
              command:
                - curl
                - -I
                - -XGET
                - http://localhost:8080/health
            failureThreshold: 12
            periodSeconds: 60
            timeoutSeconds: 30
          name: conductor-server
          ports:
            - containerPort: 8080
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
